version: "3.3"
services:
  proxy:
    build:
      context: .
    image: mohinigonawala90/proxy:dev
    depends_on:
      - item
      - order
      - user
    ports:
      - 8085:8080

  item:
    build:
      context: ../../item-service
    image: mohinigonawala90/item:dev
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      - .env

  client:
    build:
      context: ../../client
      dockerfile: Dockerfile-local
    image: mohinigonawala90/client:dev
    ports:
      - "3000:80"


  user:
    build:
      context: ../../user-service
    image: mohinigonawala90/user:dev
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      - .env

  order:
    build:
      context: ../../order-service
    image: mohinigonawala90/order:dev
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      - .env