version: "3.3"
services:
  proxy:
    build:
      context: .
    image: mohinigonawala90/proxy:dev
    depends_on:
      - product
      - order
      - user
    ports:
      - 8085:8080

  product:
    build:
      context: ../../item-service
    image: mohinigonawala90/item:dev
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      - ../../item-service/.env



  user:
    build:
      context: ../../user-service
    image: mohinigonawala90/user:dev
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      - ../../user-service/.env

  client:
    build:
      context: ../../client
      args:
        - REACT_APP_USERS_SERVICE="localhost:80"
        - REACT_APP_PRODUCTS_SERVICE="localhost:80"
    image: mohinigonawala90/client:dev
    ports:
      - "3000:80"

  order:
    build:
      context: ../../order-service
    image: mohinigonawala90/order:dev
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      - ../../order-service/.env