apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      service: client
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        service: client
        api: external
    spec:
      containers:
      - image: mohinigonawala90/client:dev
        name: client
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10

      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: client
  name: client
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 80
  selector:
    service: client
  type: LoadBalancer

